"""add_indexes_for_performance

Revision ID: 93df974c4a69
Revises: 137560ca3196
Create Date: 2026-01-21 22:29:02.080508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93df974c4a69'
down_revision: Union[str, Sequence[str], None] = '137560ca3196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_appointment_barber_date', 'appointments', ['barber_id', 'start_time'], unique=False)
    op.create_index('idx_appointment_start_time', 'appointments', ['start_time'], unique=False)
    op.create_index('idx_appointment_status', 'appointments', ['status'], unique=False)
    op.create_index('idx_client_name', 'clients', ['name'], unique=False)
    op.create_index('idx_client_phone', 'clients', ['phone'], unique=False)
    op.add_column('users', sa.Column('failed_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_attempts')
    op.drop_index('idx_client_phone', table_name='clients')
    op.drop_index('idx_client_name', table_name='clients')
    op.drop_index('idx_appointment_status', table_name='appointments')
    op.drop_index('idx_appointment_start_time', table_name='appointments')
    op.drop_index('idx_appointment_barber_date', table_name='appointments')
    # ### end Alembic commands ###
